### ISSUE TITLE
[Spike] Confirm which actions a user can perform with a lapsed LEI

### ISSUE THREAD

**Issue by billhimmelsbach** [cfpb/sbl-ux#3]
What can actions can a user perform on the platform with a lapsed LEI? (formerly known as inactive LEI)

Can a user...

- register with the platform
- log into the platform
- start filing
- upload a register file
- submit their filing

Some related questions as well:
- If a user logs in right before the filing deadline, has submitted an accurate SBLAR and given us their accurate financial institution information, but that user's institution has an inactive LEI, should they not be allowed to file?
- What should the restrictions be for the beta vs production?
- ~~Do we only care about a user's current LEI status, not their historical LEI status at the end of the activity period?~~
  - Sounds like we've solved this one since we cannot get historical lei status from the GLIEF API, so we wouldn't have a way to determine when their LEI was lapsed

**Comment by dan-padgett** [comment]
That blog post was insightful @nongarak. With regard to status, what stood out to me was this paragraph:
"It must be stressed however, that a lapsed LEI remains valid. The status ‘lapsed’ in the relevant data field of an organization’s LEI reference data simply indicates that it is behind schedule as regards renewal, i.e. re-validation of its information against third party sources."

And it sounds like the idea of "maintaining" an LEI (as the rule puts it) is likely related to ensuring that the "information recorded for the legal entity" (i.e. name and address) has been verified. 

If I'm drawing the right conclusion, then having a "lapsed" LEI is really just a flag on our end that the data associated with an LEI _might_ be outdated. If that's correct, then showing an LEI as lapsed in our system could just mean we provide some extra guidance to double check the information associated with the LEI. But because the LEI is still valid, I don't see it as any more of a blocker to filing than any other information on sign and submit that is incorrect.
