### ISSUE TITLE
Write content for the provide filing details step

### ISSUE THREAD

**Issue by natalia-fitzgerald** [cfpb/sbl-ux#4]
## Task 
Write introduction text for the provide filing details step.

## Context
In this step a filer is asked to provide information that is specific to the filing. This currently includes voluntary reporter status and filing point of contact information.

The information provided on this page meets the following criteria:
- Is always user supplied
- Is requested for every filing
- Does not live in the financial institution profile

#### Parent story (for reference)
> As a filer, I want a clear and concise introduction on the provide filing details page, so that I can understand what filing details includes, why I need to provide it, and ensure that I can enter the information correctly to avoid filing issues.

**Comment by dan-padgett** [comment]
@natalia-fitzgerald Do you want to track the content adjustments in Figma only?

**Comment by natalia-fitzgerald** [comment]
@angelcardoz @dan-padgett 
We have one more piece of content work in order to complete this work. This will have to be updated to point to provide filing details. 
<img width="657" alt="Screenshot 2024-10-24 at 1 35 20 PM" src="https://github.com/user-attachments/assets/1cc46963-3614-4595-947c-0d3ba20f511d">

**Comment by dan-padgett** [comment]
@natalia-fitzgerald Is it better to say "your institution's voluntary reporter status" instead of just "your voluntary reporter status"? I also like keeping the clarification about who might contact the institution, as in the original. Putting that together, we could have: "Next, indicate your institution's voluntary reporter status and provide contact information for a person whom the CFPB or other regulators may contact about your filing."

We could simplify further: "Next, indicate your institution's voluntary reporter status and contact information for a person whom the CFPB or other regulators may contact about your filing." (Or replace "indicate" with "provide" if that reads better.)

**Comment by natalia-fitzgerald** [comment]
@dan-padgett 
Yep, I agree with that suggestion. I reworked this to accommodate that text and to keep it to 2 lines (to align with the other cards). 

Here's where we've landed: 
<img width="763" alt="Screenshot 2024-10-25 at 11 46 37 AM" src="https://github.com/user-attachments/assets/f8b3617d-6361-42ef-9e11-28276777ee37">

**Comment by natalia-fitzgerald** [comment]
This work is completed.
